#!/bin/sh
# <oldrev> <newrev> <refname>
# Verify that author and committer emails are from a particular domain
domain=cesar.org.br
while read oldrev newrev ref
do
    echo "Checking $oldrev $newrev $ref"
    for committer in `git log --format='%ce:%ae' $oldrev..$newrev`
    do
      echo "$committer" | grep -E "[[:alnum:]]*@$domain:[[:alnum:]]*@$domain"
      if [ $? -eq 1 ] ; then
        echo "ERROR: At least 1 commit was not made using a @$domain email address."
        echo "       Please check your git logs and make sure both author and committer emails"
        echo "       are emails from @$domain and try again.\n"
        echo "To configure your e-mail address: git config user.email {seuemail}@cesar.org.br"
        echo "You may need to amend the commit: git commit --amend --reset-author"
        echo "Do this and check your git logs before pushing again. :)"
        exit 1;
      fi
    done
done
